### ISSUE TITLE
Setup Your Mac (1.5.0-rc1): Logout and Restart Attended for Enrolment Complete 

### ISSUE THREAD

**Issue by owainiorwerth** [dan-snelson/dialog-scripts#18]
Restart and Log Out Attended don't work if automatically calling the policy via Enrolment Complete policy. Restart and Log Out Attended work fine if running the script locally or if manually calling the policy via Self-Service.

Dan pointed me in the direction of his implementation notes which I hadn't seen - `we require login to Self Service (including Multi-Factor Authentication) for every other policy; enabling Setup Your Mac at Enrollment Complete would bypass the required user login on the very first policy the user experiences`

**Comment by dan-snelson** [comment]
Andrew Clark
:happymac:  [44 minutes ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669052049920089?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
this is happening because EnrollmentComplete scripts run as _mbsetupuser
:gratitude-thank-you:
1



Andrew Clark
:happymac:  [43 minutes ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669052074630689?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
image.png
 
image.png




Andrew Clark
:happymac:  [40 minutes ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669052278690379?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
so the runAsUser osascript -e 'tell app "loginwindow" to «event aevtrlgo»' command runs in the wrong context.


Dan K. Snelson
:speech_balloon:  [4 minutes ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054441647959?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
Eureka, 
[@drtaru](https://macadmins.slack.com/team/U336L08MA)
!


Dan K. Snelson
:speech_balloon:  [2 minutes ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054551430329?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
[@Owain](https://macadmins.slack.com/team/U019PNQCRBQ)
:
Please try swapping the commented code on [Line Nos. 739 - 740](https://github.com/dan-snelson/dialog-scripts/blob/v1.5.0-rc/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L739-L740).


Dan K. Snelson
:speech_balloon:  [2 minutes ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054601072919?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
(However, my current understanding is the shutdown binary’s shortest duration is 1 minute.)


Andrew Clark
:happymac:  [1 minute ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054654321089?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
you can use now


Andrew Clark
:happymac:  [< 1 minute ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054667727139?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
shutdown -r now &


Dan K. Snelson
:speech_balloon:  [< 1 minute ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054686477559?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
Yes, but I don’t think you’ll get policy logs shipped back to Jamf Pro.


Andrew Clark
:happymac:  [< 1 minute ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054700022109?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
NOPE!


Dan K. Snelson
:speech_balloon:  [< 1 minute ago](https://macadmins.slack.com/archives/C01U5MXNGG6/p1669054709023809?thread_ts=1669050392.145559&cid=C01U5MXNGG6)
(But that may not matter to some admins.)
