### ISSUE TITLE
MDM Agnostic Iteration

### ISSUE THREAD

**Issue by aanklewicz** [dan-snelson/dialog-scripts#23]
Setup Your Mac is very Jamf centric, and would be great to work with other MDMs and Munki as well for installation of data.

**Comment by acodega** [comment]
It can be tricky to support multiple MDM but it would be great to see forks of SYM.

SYM is Jamf specific because it uses Jamf specific features. Script parameters, performing a jamf binary command to run a policy or submit inventory information, etc. 

In fact the inspiration to SYM came (somehow) from my MDM Apps Deploy. I wrote it for use with Mosyle, but really it's agnostic. I'd be open to feature requests on it. I think it could be used with Munki right now, assuming Munki would run right away on a new Mac.

**Comment by WillemLangDictu** [comment]
We would like to port the "setup your Mac" to MS Intune.

**Comment by acodega** [comment]
@precursorca SYM was inspired by [MDMAppsDeploy](https://github.com/acodega/dialog-scripts), which I wrote for use with Mosyle. Check it out.

**Comment by precursorca** [comment]
LOL, I was just looking at it trying to wrap my head around it.

---
Alex Narvey
***@***.***

**Comment by acodega** [comment]
I'm not in #mosyle on Slack anymore but feel free to DM me if you have ideas/questions. Or post an Issue on my repo.

**Comment by dan-snelson** [comment]
For those not using Jamf Pro, checkout [Baseline](https://github.com/SecondSonConsulting/Baseline/blob/main/README.md).

**Comment by roto31** [comment]
For it to work on both platforms efficiently I think it would have to be tied to a script like Installomater with the Installomater script and Setup You Mac being installed directly to the machine at enrollment. Jamf Now+ has a Self Service portal so it could be called from there, "I think", JumpCloud does not have a self Service Portal yet. The thing that would need to change is the variable to call the application installation so it calls from Installomater instead of Jamf Pro. It looks like @BigMacAdmin is already on the same track with [Baseline](https://github.com/SecondSonConsulting/Baseline/blob/main/README.md).

**Comment by BigMacAdmin** [comment]
I first looked at SYM hoping I could adapt it for other MDMs, but it seemed like a major undertaking that would probably fail to have 90% of the features that make SYM awesome.

Happy to review feedback and/or pull requests on my project to get it to work for you. It's not nearly as full featured as SYM, but I need to know what people want to determine if I can spend engineering time on it.

**Comment by dan-snelson** [comment]
Thanks, @BigMacAdmin; closing as "not planned."

[Shine on, you crazy diamonds!](https://youtu.be/dQw4w9WgXcQ?t=44)
