### ISSUE TITLE
Add a user help button

### ISSUE THREAD

**Issue by master-vodawagner** [dan-snelson/dialog-scripts#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be useful to have a Help button or ? button which could be configured to show a company IT helpdesk number to call on the main Installing policy dialog screen.

**Describe alternatives you've considered**
Currently if a failure is detected, I use the bottom text field to instruct users on things to capture like which policy failed etc.  This is the helpdesk number to call

**Additional context**

**Comment by dan-snelson** [comment]
Thanks for the suggestion, @master-vodawagner.

I don't think it's currently possible to swap `--infotext` for `--infobutton`; perhaps we just open another "failed-specific" dialog.

**Comment by dan-snelson** [comment]
@master-vodawagner:

Please take [`1.2.7`](https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash
) (in the development branch) for a test-drive and let me know if it will meet your needs.

<img width="932" alt="Screenshot 2022-09-10 at 8 38 49 PM" src="https://user-images.githubusercontent.com/24623109/189510481-3fa957d7-7051-40e4-b3f6-2b3cf227b47f.png">

<img width="762" alt="Screenshot 2022-09-10 at 8 38 59 PM" src="https://user-images.githubusercontent.com/24623109/189510484-1be540be-f6fa-43c3-a8a8-8952e6ebcc79.png">

**Comment by master-vodawagner** [comment]
It certainly looks the part to fix my issues.

**Comment by dan-snelson** [comment]
Addressed by [`1.2.7`](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash)

**Comment by dan-snelson** [comment]
https://snelson.us/2022/09/setup-your-mac-via-swiftdialog-1-2-7/#dedicated-failure-dialog

**Comment by master-vodawagner** [comment]
Hmm odd, I'm using this version of code but can't get the 2nd dialog prompt to appear after a failure

**Comment by master-vodawagner** [comment]
So when I click the contact support button, the dialog window quits as expected, logging shows the failed items but the failure dialog never shows up

**Comment by dan-snelson** [comment]
Sorry its not working as expected for you, @master-vodawagner.

In a single test for me on macOS Ventura (where Sophos Endpoint currently fails to install), an unaltered download of `1.2.7` fails and shows the "Failure Detected" dialog as expected.

What are you seeing in `/private/var/log/enrollment.log` ?

**Comment by dan-snelson** [comment]
In case it helps, here's how I just tested on a device which is **already** enrolled and **successfully** completed Setup Your Mac in _my_ environment:

1. Save version [1.2.7](https://raw.githubusercontent.com/dan-snelson/dialog-scripts/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash)
2. Replace `Info.plist` with `Info.plist.failed`
3. Change [Line 39](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L39) from `debugMode="${4}"` to `debugMode="true"`
4. Elevate a Terminal session and execute the script

<img width="1136" alt="Screenshot 2022-09-15 at 11 54 01 AM" src="https://user-images.githubusercontent.com/24623109/190476563-56bfacf6-7cbe-497a-bfa4-7aa18443adea.png">

<img width="932" alt="Screenshot 2022-09-15 at 11 53 21 AM" src="https://user-images.githubusercontent.com/24623109/190476592-35d1a469-f643-427f-aa34-fdfda3cdedb8.png">

<img width="762" alt="Screenshot 2022-09-15 at 11 53 29 AM" src="https://user-images.githubusercontent.com/24623109/190476619-67d3efdb-33dc-4955-9aa8-babb8915acf5.png">

(This all may be working as expected for me because I don't have to modify anything else to test.)

**Comment by master-vodawagner** [comment]
So I’ve isolated my issue to line 422, if I hash that line out the serving prompt appears but doesn’t show the list of failed policies

**Comment by master-vodawagner** [comment]
![Uploading E202FA39-2C9F-47D0-A5D8-A8862BC2D3B8.jpeg…]()

**Comment by master-vodawagner** [comment]
![B09F2105-809E-4CB9-915E-45F28D484291](https://user-images.githubusercontent.com/39089724/190478652-b16097ad-6f2c-406d-b3bc-8f10a8248f7d.jpeg)

**Comment by dan-snelson** [comment]
Excellent find!

What value are you using for [**Completion Action**](https://snelson.us/2022/09/setup-your-mac-via-swiftdialog-1-2-7/#jamf-pro-script-payload) ? (The default is `wait`, which **requires** user-interaction.)

The list of failed policies is built on [Line 698](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L698).

**Comment by master-vodawagner** [comment]
Hi

using the default value.

I’m stumped why the failed detected prompt has none of the failed policies.

it doesn’t seem to like new lines
![C08E2AA6-F076-4E86-9363-54FA59913EFB](https://user-images.githubusercontent.com/39089724/190485512-e23796b9-f35a-42c4-8410-3a68da1aacdd.jpeg)

**Comment by master-vodawagner** [comment]
![8AD1E160-C7B3-4525-9E54-9B05E8E0D4E2](https://user-images.githubusercontent.com/39089724/190485968-5ebc7c39-9106-45b6-92c5-e66debf4ab22.jpeg)

**Comment by dan-snelson** [comment]
Please DM me your modified script via Slack.

**Comment by dan-snelson** [comment]
Which version of swiftDialog is installed?

```
❯ dialog --version
1.11.2.3095
```

**Comment by master-vodawagner** [comment]
Well I’ve fixed it, started from scratch with your version and just pasted in my changes.

No idea what went wrong 🤪

**Comment by dan-snelson** [comment]
Glad it's working, @master-vodawagner!

Thanks again for the excellent suggestion.
